Repository ibutsu/ibutsu-server, pull requests merged in 2020-10, with the labels that each got.

#47 Update the migration script to work with new psql db
  .pre-commit-config.yaml
  backend/ibutsu_server/controllers/artifact_controller.py
  backend/ibutsu_server/controllers/result_controller.py
  backend/ibutsu_server/controllers/widget_config_controller.py
  backend/ibutsu_server/db/models.py
  backend/ibutsu_server/filters.py
  backend/ibutsu_server/scripts/mongo2postgres.py
  backend/ibutsu_server/widgets/jenkins_heatmap.py
  frontend/src/app.js
  frontend/src/dashboard.js
  frontend/src/result-list.js
  frontend/src/run-list.js
  frontend/src/run.js
Labels: psql-migration

#57 Limit runs from which we determine the jenkins jobs
  backend/ibutsu_server/constants.py
  backend/ibutsu_server/scripts/mongo2postgres.py
  backend/ibutsu_server/widgets/jenkins_heatmap.py
  backend/ibutsu_server/widgets/jenkins_job_view.py
  frontend/src/views/jenkinsjob.js
Labels: performance, psql-migration

#60 Further performance improvements
  backend/ibutsu_server/constants.py
  backend/ibutsu_server/controllers/result_controller.py
  backend/ibutsu_server/controllers/run_controller.py
  backend/ibutsu_server/widgets/jenkins_heatmap.py
  frontend/src/components/result.js
  frontend/src/constants.js
  frontend/src/result-list.js
  frontend/src/utilities.js
Labels: performance

#66 Version 1.11
  backend/ibutsu_server/openapi/openapi.yaml
  backend/setup.py
  frontend/package.json
Labels: release

#68 For screenshots, the content type is 'image/png' now, just change the FE check to 'image'
  frontend/src/components/result.js
Labels: bug

#67 Group by component not metadata.component by default
  backend/ibutsu_server/constants.py
  backend/ibutsu_server/widgets/jenkins_job_analysis.py
Labels: performance

#69 Make the selected object a Select object
  frontend/src/app.js
Labels: bug

#70 Release v1.11.1
  backend/ibutsu_server/openapi/openapi.yaml
  backend/setup.py
  frontend/package.json
Labels: release

#74 Release 1.11.2
  backend/ibutsu_server/openapi/openapi.yaml
  backend/setup.py
  frontend/package.json
Labels: release

#76 Update file pruning for PSQL
  backend/ibutsu_server/tasks/db.py
Labels: backend

#77 Updates to support xfail in Ibutsu
  backend/ibutsu_server/tasks/runs.py
  frontend/src/components/result.js
Labels: enhancement

#80 Handle empty testsuites in the XML importer
  backend/ibutsu_server/controllers/import_controller.py
  backend/ibutsu_server/openapi/openapi.yaml
  backend/ibutsu_server/tasks/importers.py
  backend/ibutsu_server/test/__init__.py
  backend/ibutsu_server/test/res/empty-testsuite.xml
  backend/ibutsu_server/test/test_tasks.py
Labels: bug
