Repository ibutsu/ibutsu-server, pull requests merged in 2020-07, with the labels that each got.

#3 Make the docs requirements file match the config file
  docs/requirements.txt
Labels: documentation

#4 Fix the master_doc for Sphinx
  docs/source/conf.py
Labels: documentation

#8 Limit the number of results we can display in the results table.
  backend/ibutsu_server/constants.py
  backend/ibutsu_server/controllers/result_controller.py
  backend/ibutsu_server/openapi/openapi.yaml
  backend/setup.py
  frontend/src/result-list.js
  frontend/src/run-list.js
Labels: performance

#9 Add a link to the docs on the about modal
  frontend/src/app.js
Labels: enhancement

#11 Limit documents for reports
  backend/ibutsu_server/tasks/reports.py
  frontend/src/report-builder.js
Labels: bug, performance

#12 Add link to submit upstream issue, make links open in new tab
  frontend/src/app.js
Labels: enhancement

#13 Make links open in new tab
  frontend/src/components/decorators.js
  frontend/src/components/result.js
  frontend/src/views/jenkinsjob.js
Labels: enhancement

#14 Fix warnings for links, limit reports to 1e6 documents
  backend/ibutsu_server/tasks/reports.py
  frontend/src/app.js
  frontend/src/report-builder.js
  frontend/src/views/jenkinsjob.js
Labels: enhancement, performance

#15 Add a tooltip to the generic area chart
  frontend/src/widgets/genericarea.js
  frontend/src/widgets/genericbar.js
Labels: enhancement

#17 Apply a limit to the amount of runs from which we create the JJV
  backend/ibutsu_server/constants.py
  backend/ibutsu_server/widgets/jenkins_job_view.py
Labels: performance

#23 Check to make sure "start_time" exists when generating reports
  backend/ibutsu_server/tasks/reports.py
Labels: bug
